#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: #@ data.values.NAMESPACE
  annotations:
    #! This Secret is versioned, since we want to restart pods which rely
    #! on this object when there's an update.
    kapp.k14s.io/versioned: ""
stringData:
  secrets.yml: |
    spring:
      rabbitmq:
        username: (@= data.values.RABBITMQ_USERNAME @)
        password: (@= data.values.RABBITMQ_PASSWORD @)
      redis:
        password: (@= data.values.REDIS_PASSWORD @)
