management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  cloud:
    stream:
      bindings:
        votes:
          destination: cloudnativepoll.votes
          # Use a group to ensure a single app instance handles incoming messages.
          group: voter
        reset:
          destination: cloudnativepoll.reset
          group: instance
    services:
      # Register this app with Netflix Eureka using the container or host IP address.
      registrationMethod: direct

server:
  port: ${PORT:8081}

poll:
  choices:
    - Iron Man
    - Captain America
    - Thor
    - Captain Marvel
