management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, env
  metrics:
    export:
      wavefront:
        enabled: false

spring:
  cloud:
    stream:
      bindings:
        onVote-in-0:
          destination: cloudnativepoll.votes
          # Use a group to ensure a single app instance handles incoming messages.
          group: voter
  redis:
    # Connect to a local Redis instance by default.
    host: localhost
    port: 6379

server:
  port: ${PORT:8081}

wavefront:
  application:
    name: cloudnativepoll
    service: backend

poll:
  choices:
    - Iron Man
    - Captain America
    - Thor
    - Captain Marvel
